// <auto-generated />
namespace SimpleSportsStore.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class AddInStock : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddInStock));
        
        string IMigrationMetadata.Id
        {
            get { return "201402122011096_AddInStock"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
